# -*- coding: utf-8 -*-
"""Python Program to Swap Two Elements in a List

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FIlxVUk5SKrQVm9DNfvfH1hu_m3Ps7Ir
"""

ls=[1,3,5,7,8,9]
x=0
y=2
z=1
k=4
def swap(ls):
   ls[x],ls[y]=ls[z],ls[k]
   return ls

swap(ls)

